### ISSUE TITLE
Curl Exception

### ISSUE THREAD

**Issue by scrudge** [publicmediaplatform/pmp-wordpress#106]
Running wordpress 4.1.

Search just spins no results.  error log shows:

PHP Fatal error:  Uncaught Pmp\\Sdk\\Exception\\HostException: [0]: Unable to resolve host => GET https://api.pmp.io\n\n  thrown in /srv/www/wordpress.wbhm.org/plugins/public-media-platform/vendor/publicmediaplatform/pmpsdk/src/Pmp/Sdk/Http.php on line 106

nslookup from the server works:

# nslookup api.pmp.io
Server:		8.8.8.8
Address:	8.8.8.8#53

Non-authoritative answer:
api.pmp.io	canonical name = api-production-590641398.us-east-1.elb.amazonaws.com.
Name:	api-production-590641398.us-east-1.elb.amazonaws.com
Address: 54.225.129.11
Name:	api-production-590641398.us-east-1.elb.amazonaws.com
Address: 107.21.229.75

**Comment by cavis** [comment]
Are those `\n\n` newlines at the end of the URL actually part of the host string?  Or is that just part of the error output?

**Comment by scrudge** [comment]
I noticed them as well.  I retyped the url in the settings to make sure there wasn't an input error.  But that still didn't make them go away.

**Comment by cavis** [comment]
Well, that exception is the PHPSDK catching/rethrowing a CURL error directly from the Guzzle codebase -> https://github.com/publicmediaplatform/phpsdk/blob/master/src/Pmp/Sdk/Http.php#L133

Could there be something non-standard about your PHP Curl settings?  Maybe it's having trouble resolving the SSL cert?  (Grasping at straws).  You could try writing a [php curl script](http://php.net/manual/en/curl.examples.php#88055) that simply GETs https://api.pmp.io, and see if it can resolve the host.

@rnagle any thoughts?

**Comment by scrudge** [comment]
I've found the issue.  Must have something to do with curl and docker.  I've "fixed" it by adding a hosts file entry.  I'll go ahead close close this issue, since it's not a pmp-wordpress problem.
