### ISSUE TITLE
Hide client secret in settings

### ISSUE THREAD

**Issue by cavis** [publicmediaplatform/pmp-wordpress#14]
Treat the client_secret a bit more like a password.

- [x] Use a password field to display
- [x] After it's set, don't send the secret back to the browser via ajax/render/etc

**Comment by rnagle** [comment]
The input field is now type="password".

Once the secret is set, a link with text "Change client secret" displays instead of the field and its value. When clicked, this link displays a password input, allowing users to change it if necessary.
