### ISSUE TITLE
Text queries not getting passed correctly

### ISSUE THREAD

**Issue by cavis** [publicmediaplatform/pmp-wordpress#15]
The PMP supports advanced search syntax in the "text" field.

When I search for text `title:"google thinks"` [via the support site](https://support.pmp.io/search?text=title%3A%22google%20thinks%22&profile=story&has=image), I get back exactly one result.

But via the plugin text field, I get the expected story as the first result, and then a bunch more results.  Which makes me suspect something is getting encoded/decoded incorrectly.

**Comment by rnagle** [comment]
I agree that something's wrong here, but I can't reproduce this bug as you've described.

When I search for `title:"google thinks"` in the plugin, I don't even see that result on the first page.

Even searching for the full title (e.g., "Google Thinks We're Clueless About Cocktails, And It Wants To Help"), the story doesn't appear within the first page of results.

I'll have to dig a bit more to track this down. One question I have off the bat is, do text queries need to be url encoded when passed to the `queryDocs` function?

That is, should:

    $sdk->queryDocs(array (
      'profile' => 'story',
      'limit' => 10,
      'text' => 'google thinks',
    ));

Instead be:

    $sdk->queryDocs(array (
      'profile' => 'story',
      'limit' => 10,
      'text' => 'google%20thinks',
    ));

Any ideas on this are appreciated.

**Comment by cavis** [comment]
Hmmm... let me confirm that the SDK itself is url-encoding those quotes correctly. Seems like it may be a problem there.

**Comment by cavis** [comment]
Okay, the SDK seems to work correctly.  The guzzle `UriTemplate` handles all the encoding of query parameters, so you should be passing the regular ol' strings to it.  And running...

```php
$sdk->queryDocs(array(
  'profile' => 'story',
  'limit' => 10,
  'text' => '"google thinks"',
));
```
... returns exactly one result.  Whereas unquoting that text returns many (since without the quotes, that search is equivalent to `google OR thinks`).

Could this be an issue of double-encoding?  The javascript must url-encode the params, then PHP would need to decode them and plug them into the SDK to get the correct result.

**Comment by rnagle** [comment]
Thanks for looking into this.

It could be a double-encoding issue, depending on how jQuery actually sends data to the server. I'll take a closer look to confirm.

**Comment by rnagle** [comment]
I discovered that jQuery actually process data sent over the wire, transforming it into a query string fitting the content type "application/x-www-form-urlencoded".

Fixed this by using `JSON.stringify` on the front end and `stripslashes` + `json_decode` on the server side.

See 267095c5f4b0a302e7c63b5df5b795d6df052c43.
