### ISSUE TITLE
Javascript error in search results

### ISSUE THREAD

**Issue by cavis** [publicmediaplatform/pmp-wordpress#21]
> Uncaught TypeError: Cannot read property '0' of undefined
> http://cl.ly/image/3K1U2f2B3H0b

Happens when querying for guid `a7a9daa7-a883-42fb-8772-fb79f899cd88` in production.

https://support.pmp.io/proxy/public/docs/a7a9daa7-a883-42fb-8772-fb79f899cd88

**Comment by rnagle** [comment]
Fixed in 110f1ac0d98ebecb271ac445324e5f1743c6bb5f.
