### ISSUE TITLE
Query interface enhancements

### ISSUE THREAD

**Issue by cavis** [publicmediaplatform/pmp-wordpress#22]
Couple of thoughts on improving the query interface:

- [x] Display search "Total" next to button (replace the spinner)
- [x] Display guids next to results, to assist with debugging (probably [partial guids](http://cl.ly/image/0E2H0m0N423n) like the support searcher does)

**Comment by JNemic** [comment]
A couple of additional things that would be useful:
* Display the story published date with the stories returned in the search results
* Add and option to search by a range of dates (and perhaps a checkbox for 'today'?)

**Comment by cavis** [comment]
Merged into master.  Deploying shortly!
