### ISSUE TITLE
Option to stay on search results when creating Post

### ISSUE THREAD

**Issue by cavis** [publicmediaplatform/pmp-wordpress#24]
When drafting/publishing a Post, would be nice to leave the user on the search results page.  Maybe give them a link to the new Post, but make them click another link to go there.

**Comment by rnagle** [comment]
I am thinking we can just make this the default behavior.

So, after saving a new post, the search result the new post is based on would get the standard treatment for posts that have already been imported, including a link to edit the draft/published post in WordPress.

**Comment by cavis** [comment]
Sounds good to me.

**Comment by cavis** [comment]
Merged into master.  Releasing shortly.
