### ISSUE TITLE
Grab PMP "published" date

### ISSUE THREAD

**Issue by cavis** [publicmediaplatform/pmp-wordpress#25]
Looks like stories are currently displaying with whatever date you pulled them on.  Should be getting the `attributes.published` of the PMP story, and putting that in the Post's "Date" field.  (Hopefully that's possible).

http://cl.ly/image/3u1o3m301K1u

**Comment by rnagle** [comment]
Fixed in 631acbc453109fc1dc241c676d4a9cf30ece27e8.
