### ISSUE TITLE
PMP image metadata settings?

### ISSUE THREAD

**Issue by cavis** [publicmediaplatform/pmp-wordpress#27]
I was a bit confused at first, but it seems like wordpress is also getting exif data from images that it pulls down.  And setting the WP-image's "Description" based on that.  Is that correct?

Also looks like you are getting the basic image metadata into the featured image.

1. `attributes.title` => alt AND title
2. `attributes.description` => caption
3. `attributes.byline` => credit

But for (3)... is there no default WP-media field to set that on?  Doesn't seem to be anything in the UI for it.

**Comment by rnagle** [comment]
Yes, that's true. AFAIK, there's no such thing as image credit in WordPress. We add our own field to Largo for this purpose. We might be able to do something similar in this plugin.

**Comment by aschweigert** [comment]
Yeah, WordPress's lack of this is a huge bummer. It would be really nice to have more consistency.

**Comment by cavis** [comment]
It seems like, at some point, we'll need to assemble a big list of "PMP Plugin Custom Fields".  And the site/theme admins will be responsible for using those fields correctly.

Maybe this isn't that point.  But at some point!

**Comment by cavis** [comment]
Calling this closed.
