### ISSUE TITLE
Pulling the same story multiple times

### ISSUE THREAD

**Issue by cavis** [publicmediaplatform/pmp-wordpress#28]
Maybe an edge case - but you can currently publish the same PMP story to Wordpress multiple times.  Wondering if we should call this is a "buyer beware" kind of thing, or a bug.

**Comment by cavis** [comment]
Update: saved searches will automatically de-dup content (you can only pull a pmp-guid once).  If a WP user wants to display the Post in multiple pages of their site, they should probably use categories.

I'm thinking we should do the same with 1-off pulls.  Maybe throw up some sort of warning that the story was already pulled, and link you to it.

**Comment by rnagle** [comment]
This is done!

**Comment by cavis** [comment]
Confirmed!

![image](https://cloud.githubusercontent.com/assets/1410587/8093791/4cb10bbc-0f80-11e5-809c-cf031f491a1e.png)
