### ISSUE TITLE
Display PMP source when editing Post

### ISSUE THREAD

**Issue by cavis** [publicmediaplatform/pmp-wordpress#29]
Would be nice if there was an easy way to distinguish PMP-pulled content in the UI.  And exactly where it came from.

At a minimum, maybe displaying the guid in that "PMP" panel on the Edit Post page.

**Comment by rnagle** [comment]
We currently display the `guid` in the mega meta box. Also, the display of the mega meta box and options available differ depending on whether you own the content or not.

Is that enough to satisfy the requirements for this ticket or are we still missing something?

**Comment by cavis** [comment]
I think we're good on this ticket.  Opened #99 to ask the question I was going to ask here.
