### ISSUE TITLE
Publish plugin to wordpress.org

### ISSUE THREAD

**Issue by cavis** [publicmediaplatform/pmp-wordpress#31]
At some point, should get this published out to wordpress.org.  Ideally with some sort of tag/release based versioning system, that would automagically update out there (like how packagist.org works).  If such a thing is possible.

**Comment by cavis** [comment]
Also see #32 (issue with suhosin).  Depending on the amount of effort, could attempt to bypass that bug by composer-installing dependencies before publishing to wordpress.org.  Something like:

```shell
git clone --branch v0.1.0 git@github.com:publicmediaplatform/pmp-wordpress.git
composer install
# TODO: somehow make the plugin require vendor/autoload.php instead of pmpsdk.phar
# TODO: publish to wordpress.org
echo "profit"
```

But if that's a pain, I'm fine with just documenting the suhosin thing, for now.

**Comment by rnagle** [comment]
Here's a tutorial for [publishing a plugin to the WP directory/repository](http://code.tutsplus.com/tutorials/how-to-publish-to-the-wordpress-plugin-repository--wp-20637).

We'll need to request access to an SVN repo for the plugin (described in step 1 of the tutorial), which can take 24-48 hours for approval. It probably makes the most sense to do this with a wordpress.org account controlled by PMP.

**Comment by cavis** [comment]
I've created a PMP account, and I'll send the request as soon as we...

1. Create a readme.txt file https://wordpress.org/plugins/about/#readme
2. Finish QA-ing those recently closed bugs, then cut a release

I'm working on 2.  Can you create a short readme.txt file that passes their "validation" test?  Doesn't need to have all the tutorial-ish stuff from README.md in it, at this point.

**Comment by rnagle** [comment]
Added a simple [README.txt](https://github.com/publicmediaplatform/pmp-wordpress/blob/master/README.txt) to the repo which passes their validation. I did not include a list of contributors since I'm not entirely sure what's supposed to go there.

**Comment by cavis** [comment]
Okay, I cut a v0.2.0 release, and sent a link to that zip for approval.  We're number 81 in line!

**Comment by cavis** [comment]
Update: wordpress doesn't allow PHAR files in plugins.  So we're going to need to composer-install the SDK, zip that all together, and bundle that off to the Wordpress plugin SVN repo.  I'm currently working on an automated process for this.

**Comment by cavis** [comment]
Woh - this is done!  I did this!
