### ISSUE TITLE
Cron to draft/publish saved searches

### ISSUE THREAD

**Issue by cavis** [publicmediaplatform/pmp-wordpress#37]
Auto-draft and Auto-publish saved searches periodically.

**Comment by rnagle** [comment]
Details of how this works:

When the PMP cron task runs:
1. It starts by getting updates for any content that has been pulled from PMP.
2. It then runs the import process for any saved search queries, publishing or creating drafts of new content where appropriate.

Notes:
- This task avoids importing duplicates by iterating over each result for a saved search and checking for existing WordPress posts with the same `pmp_guid`. If the `pmp_guid` exists, the search result is NOT imported. This also means that if the same search result is encountered later in the process (e.g., the same search result appears in the result set for multiple saved search queries), the process skips importing the search result.

This puts us in a good position to implement #78.

**Comment by cavis** [comment]
Does this "avoiding-duplicate-guids" also apply to manually pulling in a Story?

**Comment by rnagle** [comment]
No, it doesn't. Currently, you can pull the same story as many times as your heart desires.

**Comment by cavis** [comment]
Is that good or bad?  I'm sort of thinking it would be worthwhile to de-dupe across the board.  (This would be a separate ticket).

**Comment by rnagle** [comment]
It's not necessarily bad, though I'm struggling to think of a case where on would actually want to import the same post multiple times.

It might be nice to have an indicator in search results to say, "Hey, you already imported this one. See: [link to edit post goes here]."

I don't really have strong feelings on this.

**Comment by cavis** [comment]
This looks good.  Avoids duplicates.

Seems like we may eventually have to re-think the PMP background cron strategy, to prevent timeouts for sites with lots of content/saved-searches.  But we'll burn that bridge when we come to it.
