### ISSUE TITLE
Saved-search documentation

### ISSUE THREAD

**Issue by cavis** [publicmediaplatform/pmp-wordpress#38]
A basic README file in the repo to explain how to use the functionality of this phase

**Comment by rnagle** [comment]
Done. See: [Saved search queries](https://github.com/publicmediaplatform/pmp-wordpress#saved-search-queries)

**Comment by cavis** [comment]
Mostly good.  But should now include "Saved Search Categories" (was added to this phase after the fact) in these docs.  Since that will probably be of most interest to users.

We're nearing a point where we (the PMP) may want to restructure the docs.  And perhaps take over ownership of some of the existing sections.  But let's get this one in there first!
