### ISSUE TITLE
Push Post to PMP

### ISSUE THREAD

**Issue by cavis** [publicmediaplatform/pmp-wordpress#41]
Push a WP-Post to the PMP:

- [x] Keep track of the GUID of the pushed story
- [x] Keep track of the GUIDs of any attached images/audio/video that was pushed along with the story
- [x] Ability to push update existing PMP content

Map story fields from post, according to best practices:

- [x] Title
- [x] Description, Content-encoded, Content-templated
- [x] Teaser
- [x] Byline
- [x] Alternate link
- [x] Item links
- [x] Collection links (w/default from Series/Property configs)
- [x] Permission links (w/default from Group configs)

Map media fields (from things embedded in post), using best practices:

- [x] Caption
- [x] Alt
- [x] Enclosure links
- [x] Permission links (same as the Story container you created above)

**Comment by rnagle** [comment]
Couple questions:

- Must a post be published in order to eligible for push to the PMP or can drafts (and otherwise unpublished stuff) be sent over?
- Do we need to set any dates based on the published, modified dates set on the WP post?
- Should pushed posts be included in the cron task that checks for updates to PMP content?

**Comment by cavis** [comment]
1. I think you should only be able to push something that is published.  Because (ideally), unpublishing or deleting a Post would also remove it from the PMP.  Unless you can think of a good use-case for pushing "draft" content to the PMP.
2. You should push the WP-published date to the PMP `attributes.published`.  You can't explicitly set the PMP created/modified dates, so I wouldn't worry about those.
3. Since you're the one who pushed the PMP content, I think it's a safe assumption that you don't need to check for upstream changes.  If we get into a situation where multiple CMS's are co-authoring a single PMP story... well then we'll need to revisit.  But that sounds complicated!

**Comment by eobanb** [comment]
I would say it would be bad practise to push drafts. Drafts are called 'drafts' for a reason.

wp_cron() is not like cron on unix. There is no background service running, therefore wp_cron() only runs when Wordpress runs. If you want true scheduled push to PMP you'll have to figure out something else.

**Comment by aschweigert** [comment]
The one use case for pushing drafts that I could see is for something like embargoed content or something you were planning to co-publish with a bunch of partner orgs with everyone pulling the trigger at the same time but wanting to give the partners the ability to review before publishing. Not sure if the security in PMP is such that that would make sense (i.e. - if something is pushed it's probably effectively "public" at that time) but this maybe something to think about (maybe not right now).

**Comment by cavis** [comment]
PMP content all has `valid.from` and `valid.to` dates, which **should** be respected by any CMS client.  (The CMS should refuse to publish something that isn't valid).  But I don't think we're quite there yet.
