### ISSUE TITLE
Automated tests

### ISSUE THREAD

**Issue by cavis** [publicmediaplatform/pmp-wordpress#44]
Not sure the easiest/best way to test a WP plugin, but would love to get some tests running via Travis CI.

Probably want to mock out PMP requests into JSON fixtures.  And ideally, these would test the full stack including javascript/backbone - maybe via Phantomjs or something.  But I'll defer to you on what's timely to do.

**Comment by rnagle** [comment]
We now have coverage for nearly every bit of the PHP in the plugin. You can see the incomplete tests here: https://github.com/publicmediaplatform/pmp-wordpress/blob/master/tests/test-plugin.php#L12-L26

My feeling here is that testing these would be equivalent to testing core functionality of WordPress. They might be helpful in the event WordPress changes its API, but writing tests for them will be laborious. I think the ROI isn't worth it.

In other test-related news -- the repository is set up on Travis CI: https://travis-ci.org/publicmediaplatform/pmp-wordpress

**Comment by rnagle** [comment]
One other thing I'll add is that there is some duplication of knowledge across tests that could be cut down by factoring that stuff out into our own base test class, extending `WP_UnitTestCase`.

**Comment by cavis** [comment]
Calling this done.  I'd love to convert everything to Codeception at some point - but that's outside the scope of this.
