### ISSUE TITLE
Group / Series / Property unset default

### ISSUE THREAD

**Issue by cavis** [publicmediaplatform/pmp-wordpress#47]
Once you've set a "Default" Group, Series or Property, there seems to be no way to unset that.

Add an "unset default" link to each of these 3 pages.

**Comment by rnagle** [comment]
Fixed with a720552b53e02bf15699b832dc87de6867b33216 and 8120f2b004d6354e5a10b6f9577a834ae659af24.

**Comment by cavis** [comment]
Confirmed!
