### ISSUE TITLE
Group / Series / Property view and change when editing post

### ISSUE THREAD

**Issue by cavis** [publicmediaplatform/pmp-wordpress#48]
Currently, Posts are just assigned to the Default Group/Series/Property you've selected.  Need some way to view/change/unset these while editing a Post.

Some sort of dropdown, with all the writeable docs of that profile in it?  Probably want to store the currently selected `group_guid` and `group_title` somewhere, so they can be displayed without having to fetch them every single time you display the Edit page.

**Comment by rnagle** [comment]
Is this absolutely essential to the next release? I ask because I don't think it was part of the original list of requirements for groups/permissions, series and properties management pages.

**Comment by cavis** [comment]
Fair enough - this is probably really an enhancement.  The current "pick a default" functionality works fine if all the content on your Wordpress site is part of the same Series/Property.

But I suspect we may see some multi-Property WP use-cases in the near term.  So I'd definitely prioritize this towards the top of the enhancements.

Any ideas on the effort level / t-shirt-size on this one?

**Comment by rnagle** [comment]
I can definitely see this being important. If we have time to tackle enhancements, I'll pick this one up first.

I'd estimate somewhere around 4 hours for this, depending on how much of the existing group, series and property code I can use without refactoring.

**Comment by cavis** [comment]
FYI, this is sort of what I was visualizing (some quick DOM hacking) -> http://cav.is/s/pdvbb.jpg

**Comment by aschweigert** [comment]
todo: figure out what all is included in the PMP metabox on the post edit screen

**Comment by rnagle** [comment]
This is done and committed to the master branch, ready for testing. It adds dropdown menus to the mega meta box for overriding the group, series and property for a post.

**Comment by cavis** [comment]
Property and Series looks good.  It did remind me that we need to get #50 done, though.  (Otherwise, it's hard to tell which collection link is which).

Group setting seems to work.  But I'm unable to unset the group.  The combobox option changes back to `--- No group ---`, even after a refresh.  But looking in the database (and looking at the doc in the support searcher), it's not actually getting unset.

**Comment by rnagle** [comment]
I think I see what's happening here. This happens for me if I have a default Group set and select "No group."

I guess "No (Group|Series|Property)" should really mean null/false and not fallback to the default for all posts.

@cavis Can you confirm this happens when you have a default value set for Groups? Also, can you confirm the desired behavior for me?

**Comment by cavis** [comment]
The "Defaults" should only apply when you're pushing a new story to the PMP.  If it already exists (has a `pmp_guid`), unsetting it should actually make it null/false.
