### ISSUE TITLE
Group / Series / Property tags

### ISSUE THREAD

**Issue by cavis** [publicmediaplatform/pmp-wordpress#49]
When setting tags on these documents, need to create them as an array.

Currently, if you put "tag1 tag2 tag3" in the text field, you get `attributes.tags = ["tag1 tag2 tag3"]`.  Should actually be `["tag1", "tag2", "tag3"]`.   So this code should probably `split()` the textfield string, and then filter out any blank strings.

**Comment by rnagle** [comment]
I *think* this is what we're currently doing.

I did a little test with the Series creation workflow, logging the data we would send for a newly created Doc. This is what I see:

![image](https://cloud.githubusercontent.com/assets/72608/7256916/824e7e3e-e817-11e4-88e3-c87976d66672.png)

As another sanity check, I inspected the data used to present the form in the WordPress dashboard and it seems to be coming back properly.

![image](https://cloud.githubusercontent.com/assets/72608/7256936/9e647e2a-e817-11e4-9ece-4f3f7b186656.png)

So I believe we are sending and receiving the proper data structures.

Perhaps there are more details for triggering the bug or some circumstance I haven't accounted for. Let me know!

**Comment by cavis** [comment]
Oh wait, are you doing comma-separated tags?  I was assuming they were space-separated.  Maybe some hint text for that field would solve my ignorance, then.

**Comment by rnagle** [comment]
Oh, I see! Yep, we should definitely add a hint. Damn my assumptions. Thanks!

**Comment by rnagle** [comment]
Added a hint in the same way that WordPress does for post tags:

![image](https://cloud.githubusercontent.com/assets/72608/7259347/44871e6a-e828-11e4-9a96-aef4db7e4dba.png)

See: 7926d3a099ffbe4e2ae51fd55bd2f9dadb4b3043.

**Comment by cavis** [comment]
Confirmed!
