### ISSUE TITLE
Newlines in contentencoded

### ISSUE THREAD

**Issue by cavis** [publicmediaplatform/pmp-wordpress#53]
Ideally, there wouldn't be all these newlines and tabs in the `contentencoded`.

So `<ol>\r\n\t<li>And</li>\r\n\t<li>Some</li>\r\n\t<li>List</li>\r\n\t<li>Items</li>\r\n</ol>` would become `<ol><li>And</li><li>Some</li><li>List</li><li>Items</li></ol>`.

This should also (hopefully) fix the `description`, removing newlines/tabs there as well.  But making sure to add spaces into the content, so the above content would go from `And\r\n\tSome\r\n\tList\r\n\tItems\r\n` to `And Some List Items`.

**Comment by cavis** [comment]
Update: Wordpress seems to handle these fine, but another client (doing a basic DOM insert of `contentencoded`) would get literal "\n" rendered.  So should probably just get rid of these.

**Comment by rnagle** [comment]
Hmm. Is it possible that we'll be removing meaningful information by doing this?

For example, with preformatted text or code tags, you probably want to preserve any \t or \n enclosed in the `<pre>` or `<code>` tags.

Just thinking out loud...

**Comment by cavis** [comment]
True.  So definitely can't remove all of them.

How does Wordpress itself render this content?  Do newlines in the Post body translate to newlines in the HTML source of the Post page?

**Comment by rnagle** [comment]
WordPress does a bunch of stuff to the post content. From [this link](http://wordpress.stackexchange.com/questions/51732/what-filters-are-applied-to-the-content-function#answer-51749):

    add_filter( 'the_content', 'wptexturize'        );
    add_filter( 'the_content', 'convert_smilies'    );
    add_filter( 'the_content', 'convert_chars'      );
    add_filter( 'the_content', 'wpautop'            );
    add_filter( 'the_content', 'shortcode_unautop'  );
    add_filter( 'the_content', 'prepend_attachment' );

The most interesting one is [`wpautop`](https://core.trac.wordpress.org/browser/tags/4.2.1/src/wp-includes/formatting.php#L373), which does a bunch of processing to remove double line breaks, double `<br>` tags and replace them with `<p>` tags. 

It also seems to do some magic tricks to preserve certain "\n" chars and insert them where they should theoretically be present.

Further, it appears to parse everything using regular expressions, which is awesome/terrifying. But, hey, it seems like it works for WP's purposes.

I think it's a really bad idea to try writing regular expressions to remove meaningless whitespace from contentencoded. Even if we manage to get the meaningless tabs, newlines, etc, we'll still be left with the original problem of some clients being unable to handle the meaningful characters.

**Comment by cavis** [comment]
Yeah, as much as I love regular expression magic, that's probably not the way to go here.

Backup up for a second: does the current `contentencoded` in the PMP exactly match what Wordpress spits out when rendering?  (Including newlines that it throws into the HTML source).

If the answer is "yes", we can probably just close this, right?

**Comment by cavis** [comment]
Also, I'm just now noticing that "The World's" contentencoded [has newlines in it](https://support.pmp.io/proxy/public/docs/9356a964-1760-439e-9af8-6bd93a5a5a4b).  Hmm...

**Comment by rnagle** [comment]
Yep, the current `contentencoded` matches what WP would print for a single article page.

**Comment by cavis** [comment]
This is done!
