### ISSUE TITLE
Image crop values

### ISSUE THREAD

**Issue by cavis** [publicmediaplatform/pmp-wordpress#59]
Where are you getting the values for `meta.crop` in pushed PMP image enclosures?

I see "thumbnail", "medium" and "original" in there.  Ideally, we'd at least attempt to map those to the best-practices [image crops](https://support.pmp.io/docs#best-practices-image-crops).  If possible.

**Comment by rnagle** [comment]
Whoops, I thought I was doing this correctly. I would relabel this a bug.

**Comment by cavis** [comment]
Bug it is!

**Comment by cavis** [comment]
I'm moving this to Phase 2, as it's sort of a "media enhancement" kind of thing.

**Comment by cavis** [comment]
:+1:
