### ISSUE TITLE
CMB2 plugin conflict with PMP push

### ISSUE THREAD

**Issue by johnsonpaul1014** [publicmediaplatform/pmp-wordpress#67]
This isn't a bug, but it is causing a problem with my installation and I wonder if you have any idea how it should be addressed.  I have another plugin installed, CMB2, that adds post meta data on the `save_post` action.  I need this to execute before your `save_post` action that does the push since the meta data may change and it is used to update the push data.  It isn't updated before the push because they have the same priority on the `add_action` call.  I resolved this temporarily by putting the priority to 99 instead of using the default 10, which is the same priority that CMB2 uses:

`add_action('save_post', 'pmp_push_to_pmp', 99);`

What do you think is the best way to resolve this?

**Comment by cavis** [comment]
I'm probably out of my depth on this one.  Any ideas @rnagle @aschweigert?

**Comment by aschweigert** [comment]
Hm, if that other plugin uses 99 (which is pretty irresponsible, imo) then you might not have a choice than to set the other action to the same priority. I'd hate to make that our default though :(

**Comment by johnsonpaul1014** [comment]
Both CMB2 and the PMP plugin were using the default of 10, which was causing the conflict.  I set the PMP to have a priority of 99 to make sure it executed after CMB2 and other plugins that potentially modify the post.  I agree, it isn't ideal to arbitrarily set some high number as the default, but I need it to be higher than CMB2.  I think a value of higher than the default would be good, just because this should really be the last thing that happens when a post is saved in case other logic needs to modify it before pushing it to the PMP.

**Comment by aschweigert** [comment]
Ah, ok, gotcha. Yeah, it might make sense to just use 11 here because, in theory, plugins shouldn't be using more than that and if we just need to make sure the push runs after their actions that should be sufficient (in most cases).
