### ISSUE TITLE
Suggestion from users - button color change

### ISSUE THREAD

**Issue by jarrigoni** [publicmediaplatform/pmp-wordpress#68]
We have installed the PMP Plugin and showed our editors where the button would be and their feedback was to change the color of the button, so it wasn't the same as the publish button. 

They were worried that they would accidentally syndicate content that should not be syndicated. We also plan to manage permission to additionally alleviate their concerns.

**Comment by cavis** [comment]
Yeah, this would be a decent short-term fix.  Longer term, I'd like to see all the PMP controls move into their own meta-box on the edit post page (see #48).

**Comment by jarrigoni** [comment]
It's own meta-box long term would be great! The team was hoping for that too.

**Comment by cavis** [comment]
This button color has been fixed in the latest version of the plugin.  #77 will cover the meta box.
