### ISSUE TITLE
Content meta-mega-box

### ISSUE THREAD

**Issue by cavis** [publicmediaplatform/pmp-wordpress#77]
Several issues have alluded to this, but it would be useful to have 1 PMP meta-box to rule them all.  This issue is just to build the meta-box, and move current PMP buttons/info from the main "Edit Post" box to there.

Also, should consolidate this with the cron-pull-checkbox widget.

Other features of the mega box will be covered elsewhere.  See #48.

**Comment by rnagle** [comment]
This is finished, but to be clear I did not include the ability to change the group, series, property as described in #48.

Motion to close this ticket!

**Comment by cavis** [comment]
Second.

**Comment by cavis** [comment]
Looks good.  But should add back in the PMP Guid/Modified display, onto pulled posts - #85
