### ISSUE TITLE
Saved search tags/categories

### ISSUE THREAD

**Issue by cavis** [publicmediaplatform/pmp-wordpress#78]
When you create/edit a saved search, you should have the ability to assign tags/categories to all Posts created from that search.

**Comment by cavis** [comment]
Note: if the PMP guid already exists as a WP-Post, any new tags/categories should be added to that Post.  So if a PMP-Story was imported by 2 different saved-searches, it would get the tags/categories for both of them.

**Comment by cavis** [comment]
Actually, after thinking about this - assigning "tags" to the saved-search isn't as useful.  Since generally those should come from the PMP-story `attributes.tags`.  So scrap that part of this ticket!

**Comment by rnagle** [comment]
This is done!

**Comment by cavis** [comment]
Works as expected.  Categories are cumulative, if an already-imported-story turns up in a different saved-search.
