### ISSUE TITLE
Saved search initial-pull limit

### ISSUE THREAD

**Issue by cavis** [publicmediaplatform/pmp-wordpress#79]
When you create a new saved-search, the plugin pulls in some amount of "initial content".  (Content that already existed when you created the search).  Then it checks for new content on a cron.

I think we've started with a default of something like "25" for the initial-pull limit.  This ticket is to make that value configurable when you're creating a new saved-search.  (But you can't edit the value on existing saved-searches, since it's no longer applicable).

**Comment by rnagle** [comment]
This done in 777dace270088b260293b062b366ff79bc021e72.

Example of the UI:
![screen shot 2015-06-08 at 11 03 31 am](https://cloud.githubusercontent.com/assets/72608/8039527/09dd94b0-0dd0-11e5-9240-18af4bae70d0.png)

**Left:** before saving a search query, the user can specify an initial pull limit.
**Right:** after the search query is saved and the cron task runs, the entire "Initial pull limit" area of the form is disabled, but displayed for posterity.

**Comment by cavis** [comment]
One qualm: the default isn't really the default - you have to explicitly fill it in.

**Comment by rnagle** [comment]
Snuck in a fix for this with #94. See [here](https://github.com/publicmediaplatform/pmp-wordpress/pull/94/files#diff-90af1c2bc46d02aae9f460a9467ed62aR373).

**Comment by cavis** [comment]
Need to QA this one.

**Comment by cavis** [comment]
Confirmed!
