### ISSUE TITLE
Duplicate posts from saved search

### ISSUE THREAD

**Issue by cavis** [publicmediaplatform/pmp-wordpress#88]
So I've setup a "Marketplace" saved search on my test site, and let it run for a couple days.  And I've been seeing a lot of duplicate posts.  http://cav.is/s/6t2tf.jpg

Seems like the Story is getting partially imported - it gets an `enclosure` custom field, but nothing else.  And since it doesn't get a `pmp_guid`, the importer continues to pull the Story until it gets the whole thing.

At least that's my guess.

**Comment by rnagle** [comment]
Does anything show up in the error log regarding this? I wonder if PHP is suddenly running out of memory (or some such thing) before it successfully pulls all posts in.

**Comment by cavis** [comment]
I see 2 recurring things in the logs:

```
PHP Fatal error:  Call to undefined function download_url() in /home/pmpbot/wordprod.pmpdev.org/public_html/wp-content/plugins/public-media-platform/inc/functions.php on line 66
```

And...

```
PHP Warning:  Invalid argument supplied for foreach() in /home/pmpbot/wordprod.pmpdev.org/public_html/wp-content/plugins/public-media-platform/inc/ajax.php on line 469
```

**Comment by cavis** [comment]
Not sure if those are related - they don't seem to be, based on where/how-often they occur in the log.

**Comment by rnagle** [comment]
So far, I can't reproduce this issue on my machine. Couple questions:

- Are you using the sandbox or production API when you see this issue?
- Can you detail the saved search configuration you're using for "Marketplace" for me?

**Comment by cavis** [comment]
I'm using production.  My search is for the collection `3e3b6243-31c6-4686-bb88-a8e8446f0c2a` (which is Marketplace the Property) and nothing else.

**Comment by cavis** [comment]
I'm going to cut a release with recent changes, and let that run for awhile.  If there aren't any duplicates, we'll call this good.

**Comment by cavis** [comment]
Still seeing this.  Just dumped all the content from wordprod.pmpdev.org, and re-created the saved search for Marketplace (the Property).  Set it to initially pull 25 stories.

Let it run through the WP HTTP-triggered cron.  Now I've got 3 duplicate Posts, and nothing else (assuming it just can't get past this one).  They all have the audio embedded, but no "PMP" custom fields.

http://cav.is/s/52dad.jpg

Nothing in the PHP logs.  And importing the Story manually works fine.

So... other ideas?

**Comment by cavis** [comment]
Seems to be related to this: https://wordpress.org/support/topic/media_handle_sideload-not-working-halts-execution

That `media_handle_sideload` is silently dying when internally-required functions aren't there.
